// src/components/WatchLater.js
import './MovieList.css';
import React, {useState, useEffect} from 'react';
import axios from 'axios';

const WatchLater = () => {
  const [favoriteMovies, setFavoriteMovies] = useState([]);

  // This function will fetch the movies from our database
  const getFavoriteMovies = async () => {
    try {
      // Make a GET request to our backend's '/favorites' endpoint
      const response = await axios.get('http://localhost:5000/favorites/');
      setFavoriteMovies(response.data); // Update state with the movies from the DB
    } catch (error) {
      console.error("Error fetching favorite movies:", error);
    }
  };

  // useEffect runs this function once when the component loads
  useEffect(() => {
    getFavoriteMovies();
  }, []); // The empty array ensures it runs only once

  return (
    <div>
      <h1>My Watch Later List</h1>
      {favoriteMovies.length > 0 ? (
        <div className="movie-grid">
          {favoriteMovies.map(movie => (
            // Note: the key is now movie._id, which is generated by MongoDB
            <div key={movie._id} className="movie-card">
              <img 
                src={movie.poster_path.startsWith('http') ? movie.poster_path : `https://image.tmdb.org/t/p/w500${movie.poster_path}`} 
                alt={movie.title} 
              />
              <h3>{movie.title}</h3>
            </div>
          ))}
        </div>
      ) : (
        <p>Your watch later list is empty. Go add some movies!</p>
      )}
    </div>
  );
};

export default WatchLater;